--DELETE FROM application_section_link WHERE active IS NULL;
DELETE FROM element_element_type_link WHERE active IS NULL;
DELETE FROM element_type_element_action_link WHERE active IS NULL;
DELETE FROM element_type_element_locator_type_link WHERE active IS NULL;
DELETE FROM engine_module_property_link WHERE active IS NULL;
DELETE FROM instruction_step_option_link WHERE active IS NULL;
DELETE FROM instruction_test_case_option_link WHERE active IS NULL;
DELETE FROM module_module_property_link WHERE active IS NULL;
DELETE FROM project_application_link WHERE active IS NULL;
DELETE FROM project_test_case_link WHERE active IS NULL;
DELETE FROM run_set_test_case_link WHERE active IS NULL;
DELETE FROM section_element_link WHERE active IS NULL;
DELETE FROM section_section_line_link WHERE active IS NULL;
DELETE FROM test_case_engine_link WHERE active IS NULL;
DELETE FROM test_case_environment_link WHERE active IS NULL;
DELETE FROM test_case_folder_test_case_link WHERE active IS NULL;
--DELETE FROM test_case_instruction_link WHERE active IS NULL;
DELETE FROM test_case_storage_link WHERE active IS NULL;

--ALTER TABLE "application_section_link" DROP COLUMN "active";
ALTER TABLE "element_element_type_link" DROP COLUMN "active";
ALTER TABLE "element_type_element_action_link" DROP COLUMN "active";
ALTER TABLE "element_type_element_locator_type_link" DROP COLUMN "active";
ALTER TABLE "engine_module_property_link" DROP COLUMN "active";
ALTER TABLE "instruction_step_option_link" DROP COLUMN "active";
ALTER TABLE "instruction_test_case_option_link" DROP COLUMN "active";
ALTER TABLE "module_module_property_link" DROP COLUMN "active";
ALTER TABLE "project_application_link" DROP COLUMN "active";
ALTER TABLE "project_test_case_link" DROP COLUMN "active";
ALTER TABLE "run_set_test_case_link" DROP COLUMN "active";
ALTER TABLE "section_element_link" DROP COLUMN "active";
ALTER TABLE "section_section_line_link" DROP COLUMN "active";
ALTER TABLE "test_case_engine_link" DROP COLUMN "active";
ALTER TABLE "test_case_environment_link" DROP COLUMN "active";
ALTER TABLE "test_case_folder_test_case_link" DROP COLUMN "active";
--ALTER TABLE "test_case_instruction_link" DROP COLUMN "active";
ALTER TABLE "test_case_storage_link" DROP COLUMN "active";