INSERT INTO "tenant" (id, username, uuid) VALUES (1, 'meowlomo', '00000000-0000-0000-0000-000000000000');

ALTER TABLE "project" ADD COLUMN tenant_id bigint;
ALTER TABLE "system_requirement_entry" ADD COLUMN tenant_id bigint;
ALTER TABLE "test_case" ADD COLUMN tenant_id bigint;
ALTER TABLE "run_set" ADD COLUMN tenant_id bigint;
ALTER TABLE "instruction_overwrite" ADD COLUMN tenant_id bigint;
ALTER TABLE "instruction" ADD COLUMN tenant_id bigint;
ALTER TABLE "application" ADD COLUMN tenant_id bigint;
ALTER TABLE "alias" ADD COLUMN tenant_id bigint;
ALTER TABLE "element" ADD COLUMN tenant_id bigint;
ALTER TABLE "dev_execution_log" ADD COLUMN tenant_id bigint;
ALTER TABLE "instruction_bundle" ADD COLUMN tenant_id bigint;
ALTER TABLE "run" ADD COLUMN tenant_id bigint;
ALTER TABLE "api_schema" ADD COLUMN tenant_id bigint;
ALTER TABLE "test_case_share_folder" ADD COLUMN tenant_id bigint;
ALTER TABLE "user_activity_log" ADD COLUMN tenant_id bigint;
ALTER TABLE "test_case_overwrite" ADD COLUMN tenant_id bigint;
ALTER TABLE "tag" ADD COLUMN tenant_id bigint;
ALTER TABLE "template" ADD COLUMN tenant_id bigint;
ALTER TABLE "section" ADD COLUMN tenant_id bigint;
ALTER TABLE "run_set_result" ADD COLUMN tenant_id bigint;
ALTER TABLE "resource" ADD COLUMN tenant_id bigint;
ALTER TABLE "property" ADD COLUMN tenant_id bigint;
ALTER TABLE "prod_instruction_result" ADD COLUMN tenant_id bigint;
ALTER TABLE "module" ADD COLUMN tenant_id bigint;
ALTER TABLE "prod_file" ADD COLUMN tenant_id bigint;
ALTER TABLE "parameter_script" ADD COLUMN tenant_id bigint;
ALTER TABLE "prod_execution_log" ADD COLUMN tenant_id bigint;
ALTER TABLE "instruction_option_entry" ADD COLUMN tenant_id bigint;
ALTER TABLE "notification" ADD COLUMN tenant_id bigint;
ALTER TABLE "email_notification_target" ADD COLUMN tenant_id bigint;
ALTER TABLE "element_type" ADD COLUMN tenant_id bigint;
ALTER TABLE "element_locator_type" ADD COLUMN tenant_id bigint;
ALTER TABLE "dev_step_log" ADD COLUMN tenant_id bigint;
ALTER TABLE "driver_entry" ADD COLUMN tenant_id bigint;
ALTER TABLE "dev_instruction_result" ADD COLUMN tenant_id bigint;
ALTER TABLE "dev_file" ADD COLUMN tenant_id bigint;

UPDATE "project" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "system_requirement_entry" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "test_case" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "run_set" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "instruction_overwrite" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "instruction" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "application" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "alias" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "element" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "dev_execution_log" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "instruction_bundle" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "run" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "api_schema" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "test_case_share_folder" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "user_activity_log" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "test_case_overwrite" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "tag" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "template" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "section" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "run_set_result" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "resource" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "property" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "prod_instruction_result" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "module" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "prod_file" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "parameter_script" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "prod_execution_log" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "instruction_option_entry" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "notification" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "email_notification_target" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "element_type" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "element_locator_type" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "dev_step_log" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "driver_entry" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "dev_instruction_result" SET tenant_id = 1 WHERE tenant_id IS NULL;
UPDATE "dev_file" SET tenant_id = 1 WHERE tenant_id IS NULL;


ALTER TABLE "project" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "system_requirement_entry" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "test_case" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "run_set" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "instruction_overwrite" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "instruction" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "application" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "alias" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "element" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "dev_execution_log" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "instruction_bundle" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "run" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "api_schema" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "test_case_share_folder" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "user_activity_log" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "test_case_overwrite" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "tag" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "template" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "section" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "run_set_result" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "resource" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "property" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "prod_instruction_result" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "module" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "prod_file" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "parameter_script" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "prod_execution_log" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "instruction_option_entry" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "notification" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "email_notification_target" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "element_type" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "element_locator_type" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "dev_step_log" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "driver_entry" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "dev_instruction_result" ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE "dev_file" ALTER COLUMN tenant_id SET NOT NULL;